import { z } from "zod";
import { MODELS, nebius, extractJson, languageInstruction } from "@/lib/nebius";
import type { Lang } from "@/lib/lang";
import type { Report } from "@/lib/schemas";
import { loadReference } from "./judge";

/**
 * Step 4 — Food Safety Management Plan (French "Plan de Maîtrise Sanitaire", PMS).
 * Generated by Nemotron Super 120B from the case file and the inspection report, so that the
 * plan addresses the actual findings rather than being a generic template.
 */

/** Flattens a model value (string, object, array) into one line of text. */
function toText(v: unknown): string {
  if (v == null) return "";
  if (typeof v === "string") return v;
  if (Array.isArray(v)) return v.map(toText).filter(Boolean).join("; ");
  if (typeof v === "object")
    return Object.entries(v as Record<string, unknown>)
      .map(([k, x]) => (typeof x === "string" || typeof x === "number" ? `${k}: ${x}` : toText(x)))
      .filter(Boolean)
      .join(" — ");
  return String(v);
}
/** List of strings that tolerates objects (Super sometimes returns {title, detail} items). */
const textList = z.preprocess((v) => (Array.isArray(v) ? v.map(toText).filter(Boolean) : v == null ? [] : [toText(v)]), z.array(z.string()));
const text = z.preprocess((v) => (v == null ? undefined : toText(v)), z.string().optional());

const CCP = z.object({
  critical_limit: text.default(""),
  monitoring: text.default(""),
  corrective_action: text.default(""),
  record: text.default(""),
});

export const Pms = z.object({
  establishment_profile: z.object({
    activity: text.default(""),
    capacity: text.default(""),
    staff: text.default(""),
    product_families: textList.default([]),
  }),
  good_hygiene_practices: z
    .array(
      z.object({
        theme: text.default(""),
        rules: textList.default([]),
        responsible: text,
        frequency: text,
        record: text,
      }),
    )
    .default([]),
  process_flow: z
    .array(
      z.object({
        step: text.default(""),
        hazards: textList.default([]),
        is_ccp: z.coerce.boolean().default(false),
        ccp: CCP.nullish(),
      }),
    )
    .default([]),
  records: z.array(z.object({ name: text.default(""), frequency: text, holder: text })).default([]),
  traceability: textList.default([]),
  nonconformity_procedure: textList.default([]),
  recall_procedure: textList.default([]),
  training_plan: textList.default([]),
  /** Ordered 30-day action plan derived from the inspection findings. */
  priority_actions: z.array(z.object({ action: text.default(""), deadline: text.default(""), addresses: text })).default([]),
});
export type Pms = z.infer<typeof Pms>;

export interface PmsInput {
  establishment: string;
  caseText: string;
  report: Report;
  lang: Lang;
}

export interface PmsResult {
  pms: Pms;
  model: string;
  durationMs: number;
  usage?: { prompt_tokens: number; completion_tokens: number; total_tokens: number };
}

function buildSystem(reference: string, lang: Lang): string {
  return `You are a food-safety consultant writing the Food Safety Management Plan (French PMS: Plan de
Maîtrise Sanitaire, required by Regulation (EC) 852/2004 art. 5) for a commercial restaurant.
You have the inspection case file and the simulated inspection report. Write a plan that is
SPECIFIC to this establishment: reuse its equipment names, its product families, and make sure
every non-compliance of the report is addressed by a practice, a CCP, a record or a priority
action. Be concrete and operational (who, what, when, how, which record), not academic.
Follow the HACCP method (7 principles) and the chapters of the reference below.
${languageInstruction(lang)}

=== REFERENCE ===
${reference}
=== END OF REFERENCE ===

Reply ONLY with a JSON object:
{
  "establishment_profile": {"activity": "...", "capacity": "...", "staff": "...", "product_families": ["..."]},
  "good_hygiene_practices": [
    {"theme": "Staff hygiene|Premises and equipment|Cleaning and disinfection|Pest control|Water|Temperatures and cold chain|Receiving and storage|Waste|Allergens|Traceability", "rules": ["..."], "responsible": "...", "frequency": "...", "record": "..."}
  ],
  "process_flow": [
    {"step": "Receiving", "hazards": ["..."], "is_ccp": true, "ccp": {"critical_limit": "...", "monitoring": "...", "corrective_action": "...", "record": "..."}},
    {"step": "Cold storage", "hazards": ["..."], "is_ccp": true, "ccp": {...}},
    {"step": "...", "hazards": ["..."], "is_ccp": false, "ccp": null}
  ],
  "records": [{"name": "...", "frequency": "...", "holder": "..."}],
  "traceability": ["..."],
  "nonconformity_procedure": ["..."],
  "recall_procedure": ["..."],
  "training_plan": ["..."],
  "priority_actions": [{"action": "...", "deadline": "immediate|24h|7d|30d", "addresses": "NC-01"}]
}
Keep it dense: 6-10 hygiene themes, 8-12 process steps (3-5 CCPs), 6-10 records.`;
}

export async function generatePms(input: PmsInput): Promise<PmsResult> {
  const reference = await loadReference();
  const t0 = Date.now();
  const model = MODELS.judgeFallback; // Super 120B: fast enough for a long structured document
  const res = await nebius.chat.completions.create({
    model,
    temperature: 0.2,
    max_tokens: 14000,
    messages: [
      { role: "system", content: buildSystem(reference, input.lang) },
      {
        role: "user",
        content: `# Establishment: ${input.establishment}\n\n${input.caseText}\n\n# Simulated inspection report\n${JSON.stringify(input.report, null, 1)}`,
      },
    ],
  });
  if (res.choices[0]?.finish_reason === "length") throw new Error(`reply truncated (max_tokens), ${res.usage?.completion_tokens} tokens generated`);
  const pms = Pms.parse(extractJson(res.choices[0]?.message?.content ?? ""));
  return { pms, model, durationMs: Date.now() - t0, usage: res.usage };
}
